import type { Skill } from "./types"

// ─────────────────────────────────────────────────────────────
// LEVEL 1 — EXPLORER (6–9)
// ─────────────────────────────────────────────────────────────

const EXPLORER_SKILLS: Skill[] = [
  {
    id: "money-awareness-1",
    name: "Czym są pieniądze?",
    description: "Poznaj historię pieniędzy i dlaczego ich używamy",
    ageGroup: "EXPLORER",
    difficulty: "EASY",
    prerequisites: [],
    unlockXP: 0,
    category: "MONEY_AWARENESS",
    xpReward: 30,
    isPremium: false,
    estimatedMinutes: 8,
    tags: ["pieniądze", "historia", "podstawy"],
  },
  {
    id: "money-awareness-2",
    name: "Monety i banknoty",
    description: "Rozpoznaj wartości monet i banknotów",
    ageGroup: "EXPLORER",
    difficulty: "EASY",
    prerequisites: ["money-awareness-1"],
    unlockXP: 0,
    category: "MONEY_AWARENESS",
    xpReward: 30,
    isPremium: false,
    estimatedMinutes: 10,
    tags: ["monety", "banknoty", "wartości"],
  },
  {
    id: "money-awareness-3",
    name: "Skąd biorą się pieniądze?",
    description: "Dowiedz się, że pieniądze zarabia się pracą",
    ageGroup: "EXPLORER",
    difficulty: "EASY",
    prerequisites: ["money-awareness-1"],
    unlockXP: 0,
    category: "MONEY_AWARENESS",
    xpReward: 35,
    isPremium: false,
    estimatedMinutes: 10,
    tags: ["praca", "zarabianie", "rodzice"],
  },
  {
    id: "saving-basics-1",
    name: "Skarbonka — pierwszy krok",
    description: "Naucz się odkładać część pieniędzy do skarbonki",
    ageGroup: "EXPLORER",
    difficulty: "EASY",
    prerequisites: ["money-awareness-2"],
    unlockXP: 30,
    category: "SAVING",
    xpReward: 35,
    isPremium: false,
    estimatedMinutes: 8,
    tags: ["skarbonka", "oszczędzanie", "nawyk"],
  },
  {
    id: "saving-basics-2",
    name: "Mały cel = duży sukces",
    description: "Oszczędzaj na coś, czego naprawdę chcesz",
    ageGroup: "EXPLORER",
    difficulty: "EASY",
    prerequisites: ["saving-basics-1"],
    unlockXP: 65,
    category: "SAVING",
    xpReward: 40,
    isPremium: false,
    estimatedMinutes: 10,
    tags: ["cel", "oszczędzanie", "motywacja"],
  },
  {
    id: "needs-wants-1",
    name: "Potrzeby i zachcianki",
    description: "Rozróżniaj co potrzebujesz a czego tylko chcesz",
    ageGroup: "EXPLORER",
    difficulty: "EASY",
    prerequisites: ["money-awareness-3"],
    unlockXP: 35,
    category: "DECISION_MAKING",
    xpReward: 40,
    isPremium: false,
    estimatedMinutes: 10,
    tags: ["potrzeby", "zachcianki", "wybór"],
  },
  {
    id: "needs-wants-2",
    name: "Mądre zakupy",
    description: "Jak robić zakupy z głową i nie żałować wyborów",
    ageGroup: "EXPLORER",
    difficulty: "MEDIUM",
    prerequisites: ["needs-wants-1", "saving-basics-1"],
    unlockXP: 75,
    category: "DECISION_MAKING",
    xpReward: 45,
    isPremium: false,
    estimatedMinutes: 12,
    tags: ["zakupy", "decyzja", "wybór"],
  },
]

// ─────────────────────────────────────────────────────────────
// LEVEL 2 — LEARNER (10–12)
// ─────────────────────────────────────────────────────────────

const LEARNER_SKILLS: Skill[] = [
  {
    id: "budget-basics-1",
    name: "Co to jest budżet?",
    description: "Poznaj ideę planowania wydatków",
    ageGroup: "LEARNER",
    difficulty: "EASY",
    prerequisites: [],
    unlockXP: 0,
    category: "BUDGETING",
    xpReward: 40,
    isPremium: false,
    estimatedMinutes: 10,
    tags: ["budżet", "planowanie", "podstawy"],
  },
  {
    id: "budget-basics-2",
    name: "Mój budżet kieszonkowy",
    description: "Stwórz własny plan wydatków z kieszonkowego",
    ageGroup: "LEARNER",
    difficulty: "MEDIUM",
    prerequisites: ["budget-basics-1"],
    unlockXP: 40,
    category: "BUDGETING",
    xpReward: 50,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["kieszonkowe", "budżet", "plan"],
  },
  {
    id: "budget-basics-3",
    name: "Wpływy i wydatki",
    description: "Śledź swoje pieniądze — co wpada, co wypada",
    ageGroup: "LEARNER",
    difficulty: "MEDIUM",
    prerequisites: ["budget-basics-2"],
    unlockXP: 90,
    category: "BUDGETING",
    xpReward: 55,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["wpływy", "wydatki", "śledzenie"],
  },
  {
    id: "goal-setting-1",
    name: "Cel finansowy",
    description: "Jak wyznaczać konkretne cele i do nich dążyć",
    ageGroup: "LEARNER",
    difficulty: "EASY",
    prerequisites: ["budget-basics-1"],
    unlockXP: 40,
    category: "GOALS",
    xpReward: 45,
    isPremium: false,
    estimatedMinutes: 12,
    tags: ["cel", "planowanie", "motywacja"],
  },
  {
    id: "goal-setting-2",
    name: "Plan oszczędzania",
    description: "Oblicz ile tygodni potrzebujesz na swój cel",
    ageGroup: "LEARNER",
    difficulty: "MEDIUM",
    prerequisites: ["goal-setting-1", "budget-basics-2"],
    unlockXP: 90,
    category: "GOALS",
    xpReward: 55,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["oszczędzanie", "plan", "obliczenia"],
  },
  {
    id: "delayed-gratification-1",
    name: "Poczekaj i wygraj więcej",
    description: "Dlaczego czekanie na nagrodę się opłaca",
    ageGroup: "LEARNER",
    difficulty: "MEDIUM",
    prerequisites: ["goal-setting-1"],
    unlockXP: 85,
    category: "GOALS",
    xpReward: 55,
    isPremium: false,
    estimatedMinutes: 12,
    tags: ["cierpliwość", "odroczona nagroda", "psychologia"],
  },
  {
    id: "delayed-gratification-2",
    name: "Efekt kuli śnieżnej",
    description: "Małe oszczędności + czas = wielkie sumy",
    ageGroup: "LEARNER",
    difficulty: "HARD",
    prerequisites: ["delayed-gratification-1", "budget-basics-3"],
    unlockXP: 145,
    category: "SAVING",
    xpReward: 65,
    isPremium: true,
    estimatedMinutes: 18,
    tags: ["procentu składany", "czas", "wzrost"],
  },
]

// ─────────────────────────────────────────────────────────────
// LEVEL 3 — ACHIEVER (13–15)
// ─────────────────────────────────────────────────────────────

const ACHIEVER_SKILLS: Skill[] = [
  {
    id: "income-sources-1",
    name: "Jak można zarabiać?",
    description: "Poznaj różne źródła dochodu dostępne dla nastolatka",
    ageGroup: "ACHIEVER",
    difficulty: "EASY",
    prerequisites: [],
    unlockXP: 0,
    category: "EARNING",
    xpReward: 50,
    isPremium: false,
    estimatedMinutes: 12,
    tags: ["dochód", "zarabianie", "praca"],
  },
  {
    id: "income-sources-2",
    name: "Aktywny vs pasywny dochód",
    description: "Różnica między zarabianiem własnym czasem a pracą pieniędzy",
    ageGroup: "ACHIEVER",
    difficulty: "MEDIUM",
    prerequisites: ["income-sources-1"],
    unlockXP: 50,
    category: "EARNING",
    xpReward: 60,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["dochód pasywny", "aktywny", "różnica"],
  },
  {
    id: "investing-concepts-1",
    name: "Co to jest inwestowanie?",
    description: "Zrozum ideę pracy pieniędzy na siebie",
    ageGroup: "ACHIEVER",
    difficulty: "MEDIUM",
    prerequisites: ["income-sources-2"],
    unlockXP: 110,
    category: "INVESTING",
    xpReward: 70,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["inwestowanie", "kapitał", "podstawy"],
  },
  {
    id: "investing-concepts-2",
    name: "Procent składany",
    description: "Jak czas i reinwestowanie tworzą bogactwo",
    ageGroup: "ACHIEVER",
    difficulty: "HARD",
    prerequisites: ["investing-concepts-1"],
    unlockXP: 180,
    category: "INVESTING",
    xpReward: 80,
    isPremium: true,
    estimatedMinutes: 20,
    tags: ["procent składany", "wzrost", "czas"],
  },
  {
    id: "risk-understanding-1",
    name: "Ryzyko i nagroda",
    description: "Każda decyzja finansowa niesie ryzyko — jak je oceniać",
    ageGroup: "ACHIEVER",
    difficulty: "MEDIUM",
    prerequisites: ["investing-concepts-1"],
    unlockXP: 180,
    category: "RISK",
    xpReward: 70,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["ryzyko", "nagroda", "decyzja"],
  },
  {
    id: "risk-understanding-2",
    name: "Dywersyfikacja",
    description: "Nie wkładaj wszystkich jajek do jednego koszyka",
    ageGroup: "ACHIEVER",
    difficulty: "HARD",
    prerequisites: ["risk-understanding-1", "investing-concepts-2"],
    unlockXP: 260,
    category: "RISK",
    xpReward: 85,
    isPremium: true,
    estimatedMinutes: 20,
    tags: ["dywersyfikacja", "portfel", "bezpieczeństwo"],
  },
]

// ─────────────────────────────────────────────────────────────
// LEVEL 4 — MASTER (16–18)
// ─────────────────────────────────────────────────────────────

const MASTER_SKILLS: Skill[] = [
  {
    id: "personal-finance-1",
    name: "Finanse osobiste — przegląd",
    description: "Kompleksowy obraz zarządzania własnymi finansami",
    ageGroup: "MASTER",
    difficulty: "MEDIUM",
    prerequisites: [],
    unlockXP: 0,
    category: "PERSONAL_FINANCE",
    xpReward: 70,
    isPremium: false,
    estimatedMinutes: 18,
    tags: ["finanse osobiste", "przegląd", "system"],
  },
  {
    id: "personal-finance-2",
    name: "Fundusz awaryjny",
    description: "Dlaczego 3–6 miesięcy wydatków w rezerwie to podstawa",
    ageGroup: "MASTER",
    difficulty: "MEDIUM",
    prerequisites: ["personal-finance-1"],
    unlockXP: 70,
    category: "PERSONAL_FINANCE",
    xpReward: 75,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["fundusz awaryjny", "bezpieczeństwo", "rezerwa"],
  },
  {
    id: "personal-finance-3",
    name: "Podatki — co każdy powinien wiedzieć",
    description: "Podstawy systemu podatkowego i rozliczeń",
    ageGroup: "MASTER",
    difficulty: "HARD",
    prerequisites: ["personal-finance-2"],
    unlockXP: 145,
    category: "PERSONAL_FINANCE",
    xpReward: 90,
    isPremium: true,
    estimatedMinutes: 25,
    tags: ["podatki", "PIT", "rozliczenie"],
  },
  {
    id: "budget-optimization-1",
    name: "Metoda 50/30/20",
    description: "Klasyczna reguła podziału dochodów",
    ageGroup: "MASTER",
    difficulty: "MEDIUM",
    prerequisites: ["personal-finance-1"],
    unlockXP: 70,
    category: "BUDGETING",
    xpReward: 75,
    isPremium: false,
    estimatedMinutes: 15,
    tags: ["50/30/20", "podział", "budżet"],
  },
  {
    id: "budget-optimization-2",
    name: "Zero-based budgeting",
    description: "Zaawansowana metoda — każda złotówka ma przypisaną rolę",
    ageGroup: "MASTER",
    difficulty: "HARD",
    prerequisites: ["budget-optimization-1"],
    unlockXP: 145,
    category: "BUDGETING",
    xpReward: 90,
    isPremium: true,
    estimatedMinutes: 22,
    tags: ["zero-based", "budżet", "zaawansowany"],
  },
  {
    id: "real-world-decisions-1",
    name: "Kredyt — kiedy, czy i jak?",
    description: "Kiedy zadłużenie ma sens, a kiedy niszczy finanse",
    ageGroup: "MASTER",
    difficulty: "HARD",
    prerequisites: ["personal-finance-2", "budget-optimization-1"],
    unlockXP: 145,
    category: "DECISION_MAKING",
    xpReward: 95,
    isPremium: true,
    estimatedMinutes: 25,
    tags: ["kredyt", "dług", "decyzja"],
  },
  {
    id: "real-world-decisions-2",
    name: "Własna firma — podstawy",
    description: "Czego potrzebujesz żeby zacząć zarabiać na własną rękę",
    ageGroup: "MASTER",
    difficulty: "HARD",
    prerequisites: ["real-world-decisions-1", "personal-finance-3"],
    unlockXP: 240,
    category: "EARNING",
    xpReward: 120,
    isPremium: true,
    estimatedMinutes: 30,
    tags: ["przedsiębiorczość", "firma", "start"],
  },
]

export const ALL_SKILLS: Skill[] = [
  ...EXPLORER_SKILLS,
  ...LEARNER_SKILLS,
  ...ACHIEVER_SKILLS,
  ...MASTER_SKILLS,
]

export const SKILLS_BY_ID: Readonly<Record<string, Skill>> = Object.fromEntries(
  ALL_SKILLS.map((s) => [s.id, s])
)

export const SKILLS_BY_AGE_GROUP: Readonly<Record<string, Skill[]>> = {
  EXPLORER: EXPLORER_SKILLS,
  LEARNER: LEARNER_SKILLS,
  ACHIEVER: ACHIEVER_SKILLS,
  MASTER: MASTER_SKILLS,
}
